### ISSUE TITLE
Error loading the component 

### ISSUE THREAD

**Issue by utpalthakar** [radireddy/ember-bootstrap-table#1]
Getting below error after including this component in my template
"ember.debug.js:39859 Uncaught Error: Cannot call `compile` without the template compiler loaded. Please load `ember-template-compiler.js` prior to calling `compile`."
I have installed ember-template-compiler.js already. Is there anything else thats missing ?
Update: My mistake. Didn't do app import as mentioned in the install instructions. Please close the issue.
Thanks

**Comment by radireddy** [comment]
have you included it in your ember-cli-build.js file? if not add below line in it.

app.import('bower_components/ember/ember-template-compiler.js');

**Comment by radireddy** [comment]
not a issue need to add app import in ember-cli-build.js

app.import('bower_components/ember/ember-template-compiler.js');
